### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter'

### ISSUE THREAD

**Issue by gggzzz1212** [shroominic/codeinterpreter-api#54]
Traceback (most recent call last):
  File "/home/Group/gf/src/tool_learning/codeinterpreter-api/examples/show_bitcoin_chart.py", line 28, in <module>
    asyncio.run(main())
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/Group/gf/src/tool_learning/codeinterpreter-api/examples/show_bitcoin_chart.py", line 13, in main
    async with CodeInterpreterSession(openai_api_key="3951538c13c445979954a6ad2d62875f") as session:
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 194, in __aenter__
    await self.astart()
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 32, in astart
    await self.codebox.astart()
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/site-packages/codeboxapi/box/localbox.py", line 112, in astart
    self.subprocess = await asyncio.create_subprocess_exec(
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/base_events.py", line 1676, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/envs/lc_code_interpreter/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbd2ceb7be0>

进程已结束,退出代码1

**Comment by shroominic** [comment]
Make sure jupyter-kernel-gateway is installed. Normally this should get installed automatically when you install the package because codeinterpreterapi depends on codeboxapi, which depends on jupyter-kernel-gateway. 
You should be able to fix this by typing `pip install jupyter-kernel-gateway`

**Comment by gggzzz1212** [comment]
```
pip list | grep jupyter-kernel-gateway
jupyter-kernel-gateway    2.5.2

```
I have installed jupyter-kernel-gateway in the environment, but still encounter the above error.

> Make sure jupyter-kernel-gateway is installed. Normally this should get installed automatically when you install the package because codeinterpreterapi depends on codeboxapi, which depends on jupyter-kernel-gateway. You should be able to fix this by typing `pip install jupyter-kernel-gateway`
