### ISSUE TITLE
Exception: Error: 403 {"detail":"Wrong API-KEY: must start with 'sk-'"}

### ISSUE THREAD

**Issue by mingcizzz** [shroominic/codeinterpreter-api#56]
Traceback (most recent call last):
  File "/Users/zhangmingchi/codeinterpreter-api/examples/test.py", line 28, in <module>
    asyncio.run(main())
  File "/Users/zhangmingchi/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/zhangmingchi/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/zhangmingchi/codeinterpreter-api/examples/test.py", line 6, in main
    async with CodeInterpreterSession() as session:
  File "/Users/zhangmingchi/codeinterpreter-api/cienv/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 204, in __aenter__
    await self.astart()
  File "/Users/zhangmingchi/codeinterpreter-api/cienv/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 39, in astart
    await self.codebox.astart()
  File "/Users/zhangmingchi/codeinterpreter-api/cienv/lib/python3.9/site-packages/codeboxapi/box/codebox.py", line 67, in astart
    self.id = (await abase_request(
  File "/Users/zhangmingchi/codeinterpreter-api/cienv/lib/python3.9/site-packages/codeboxapi/utils.py", line 87, in abase_request
    return await handle_response_async(response)
  File "/Users/zhangmingchi/codeinterpreter-api/cienv/lib/python3.9/site-packages/codeboxapi/utils.py", line 51, in handle_response_async
    raise Exception(f"Error: {response.status} {await response.text()}")
Exception: Error: 403 {"detail":"Wrong API-KEY: must start with 'sk-'"}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa9619a2730>
Unclosed connector

**Comment by mingcizzz** [comment]
have set the correct open ai api key, all examples show the same error
OPENAI_API_KEY=sk-dsdfsdgdsgdsgsddgsdgdsgad
CODEBOX_API_KEY= # your codebox api key (optional, required for production)
VERBOSE=True # set to True to enable verbose logging

**Comment by shroominic** [comment]
Hey I think python is setting the CODEBOX_API_KEY with the value " # your codebox api key (optional, required for production)" so to fix this just remove the CODEBOX_API_KEY or comment it out from the beginning of the line

```
OPENAI_API_KEY=sk-dsdfsdgdsgdsgsddgsdgdsgad
VERBOSE=True
# CODEBOX_API_KEY=
``` 
So ideally it should look like this :)
