### ISSUE TITLE
TypeError: object.__new__() takes exactly one argument (the type to instantiate)

### ISSUE THREAD

**Issue by Happiness777** [shroominic/codeinterpreter-api#76]
Hello, I tried to run the front-end in Termux, and it seems to work fine, until I try to chat with the bot. The moment I hit the send button, I get this error:
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/frontend/app.py", line 32, in <module>
    asyncio.run(get_images(input_text, files=uploaded_files_list))
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/frontend/utils.py", line 25, in get_images
    async with CodeInterpreterSession(model="gpt-3.5-turbo") as session:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/codeinterpreterapi/session.py", line 50, in __init__
    self.codebox = CodeBox(**kwargs)
                   ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/venv/lib/python3.11/site-packages/codeboxapi/box/codebox.py", line 61, in __new__
    return LocalBox(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/git-projects/codeinterpreter-api/venv/lib/python3.11/site-packages/codeboxapi/box/localbox.py", line 43, in __new__
    cls._instance = super().__new__(cls, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

My python version is 3.11.4, and I have the latest (as of 9.8.2023) version of codeinterpreterapi, the 0.0.10.
Oh, and I'm using venv.

Am I doing something wrong, or the module is broken for Termux, apparently?

**Comment by shroominic** [comment]
Hey I think this is fixed now in v0.0.11 maybe you can try this and if not write me again :)

**Comment by Happiness777** [comment]
Works like a charm 😁
