### ISSUE TITLE
asyncio.exceptions.TimeoutError

### ISSUE THREAD

**Issue by yoshinaga0106** [shroominic/codeinterpreter-api#87]
I cloned your repository (directory is `/Users/yoshinaga/Work/Project/`), and set `OPENAI_API_KEY` (`export OPENAI_API_KEY="sk-xxxxx"`) and executed the example (`python examples/analyze_dataset.py`).
However, the following error was occured.
How should I deal with this?

```
yoshinaga@mG37QYXD7HF codeinterpreter-api % python examples/analyze_dataset.py 
Traceback (most recent call last):
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/client.py", line 323, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio. exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yoshinaga/Work/Project/codeinterpreter-api/examples/analyze_dataset.py", line 24, in <module>
    asyncio.run(main())
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/yoshinaga/Work/Project/codeinterpreter-api/examples/analyze_dataset.py", line 6, in main
    async with CodeInterpreterSession() as session:
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 194, in __aenter__
    await self.astart()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/codeinterpreterapi/session.py", line 32, in astart
    await self.codebox.astart()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/codeboxapi/box/localbox.py", line 139, in astart
    self.ws = await ws_connect(
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/Users/yoshinaga/.pyenv/versions/3.9.16/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x13db47a60>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x13dc60a60>, 1.316770625)]']
connector: <aiohttp.connector.TCPConnector object at 0x13dc69100>
```

**Comment by venkateshbabusekar** [comment]
I face a similar issue. Is there a fix for it ?

**Comment by Lucas123912** [comment]
me too

**Comment by yoshinaga0106** [comment]
Could you please assign this task to any developer?
@shroominic

**Comment by zakrian07** [comment]
need udpate on it
